### PR TITLE
feat: add ingress support and SSL option

### PR DESCRIPTION
**Pull request by rchl**
- support ingress
 - add SSL option (requires HA instance to have configured certificates)

### CODE REVIEW

**Comment by alphasixtyfive** [comment]
Great work!

**Comment by rchl** [comment]
I was writing some lengthy comment but I'll spare that since you've integrated already :)

I Will just note that in ingress mode, it should just work without any API issues, but of course, it loads inside HA UI so it might be undesired in some use-cases.

As for opening directly using the exposed port, it will also automatically set up `serverUrl` and `wsUrl` but I'm not sure if the detected domain will be correct in all cases. This depends on how the user has configured the "Internal" and "External" URL, if at all.

Also not sure if SSL will work since I need to test that on my real installation (only tested in local docker dev setup).

**Comment by alphasixtyfive** [comment]
Thank you, I will try to test it as much as possible.

**Comment by rchl** [comment]
And note that when the add-on has `"ingress": true` in the config, like this one does now then the "OPEN WEB UI" button always opens in ingress mode so opening directly is more difficult.

**Comment by rchl** [comment]
Released https://github.com/resoai/TileBoard-addon/releases/tag/v1.1.0

**Comment by rchl** [comment]
Warning: released from the wrong branch so the docker image was not built. It would look like 1.1.0 was installed in HA but would use old code... Should be fixed now with https://github.com/resoai/TileBoard-addon/releases/tag/v1.2.0

**Comment by rchl** [comment]
https://github.com/resoai/TileBoard-addon/releases/tag/v1.2.1 fixed websocket URL in direct mode

**Comment by alphasixtyfive** [comment]
I figured I'll not open an issue to keep my thoughts and observations semi-privately here. So far it is working great and one can specify port number in the config for add-on to function like it used to before ingress. I did notice that with the ingress our usual long-press which opened up history is now redirecting to HA's login prompting for username and password.

**Comment by rchl** [comment]
Should be fixed in https://github.com/resoai/TileBoard-addon/releases/tag/v1.2.2

**Comment by alphasixtyfive** [comment]
I can confirm that it is working fine now. Thanks!

**Pull request merged**
